Authorization
Cowboy-Bebop-HR/Blue-Ocean pull request #8
Opened 2022-08-15 22:53 UTC by ntjohns10

basic authorization and player complete.  If there is not token, user is brought to login page, upon successful login user is brought to player page which should automatically begin playing  song.

Make sure your .env file has the spotify client_id and spotify user_secret.

2022-08-15 23:03 UTC, Panlord requested changes
Code looks good overall, but I've left several comments. Once they have been addressed, I will be happy to approve of these changes.

2022-08-15 23:03 UTC, Panlord commented on client/src/components/App.jsx
> +    </div>
Regarding these changes, wouldn't you want to resolve this conflict with something like
```
<SongContext...>
   <SearchBar />
  <Landing />
</SongContext>
```
I think with this here, you're deleting the SearchBar component that others wrote. That is, unless I am misinterpreting the code and/or this is intended.

2022-08-15 23:03 UTC, Panlord commented on client/src/components/landing.jsx
> +      { (token === '') ? <Login/> : <Player token={token} />}
Your conditional rendering of this using a ternary  operator is clever and looks nice here. I commend you on this.

2022-08-15 23:11 UTC, Panlord commented on client/src/components/App.jsx
> +    </div>
Turns out that this was indeed an issue with my own interpretation. Indeed we do not want the search bar in the landing page. I would just let the SearchBar team know that this SearchBar component will need to be relocated elsewhere.

2022-08-15 23:11 UTC, Panlord approved these changes
Approved

2022-08-16 00:25 UTC, toanddao approved these changes
This looks great

2022-08-16 00:25 UTC, merged